baseURL = "https://desplats.com.ar/"
languageCode = "en-us"
title = "Florencia Desplats"
theme = "aerial"

[params]
  name = "Florencia Desplats"
  about = "My personal and professional networks"
  copyright = "Untitled"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/flor_desplats"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/florenciadesplats"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://instagram.com/flor_desplats"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/flordesplats/"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:fdesplats@gmail.com"
